### ISSUE TITLE
IP_Adapter error

### ISSUE THREAD

**Issue by doogyhatts** [ykk648/AnimateDiff#14]
I tried to enable IP_Adapter but got this error instead.

> init IPAdapter model.
IPAdapter find 32 attn layers
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/content/AnimateDiff/scripts/animate.py", line 235, in <module>
    main(args)
  File "/content/AnimateDiff/scripts/animate.py", line 108, in main
    ipap = IPAdapterPlus(pipeline, f'{args.ip_adapter_model_dir}/clip_image_encoder',
  File "/content/AnimateDiff/ip_adapter/ip_adapter.py", line 58, in __init__
    self.image_encoder = CLIPVisionModelWithProjection.from_pretrained(self.image_encoder_path).to(self.device,
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 2389, in from_pretrained
    resolved_config_file = cached_file(
  File "/usr/local/lib/python3.10/dist-packages/transformers/utils/hub.py", line 429, in cached_file
    resolved_file = hf_hub_download(
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 110, in _inner_fn
    validate_repo_id(arg_value)
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 158, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': 'models/IP_Adapter/clip_image_encoder'. Use `repo_type` argument if needed.

**Comment by doogyhatts** [comment]
I figured out that I need to create a folder named "clip_image_encoder" and copy the files from the folder "image_encoder" found in h94's HF into there.
