### ISSUE TITLE
Bug : Problem with images smaller than 512*512

### ISSUE THREAD

**Issue by hajiarab1988** [ykk648/AnimateDiff#18]
Hi Dear @ykk648,

I have been using your repository for a while, and I recently noticed some significant changes in the code and the requirements for image sizes. While I understand the need for updates and improvements, the recent changes have caused some issues for me due to my limited GPU VRAM.

Previously, I was able to work with images that were resized to 480x480 pixels to fit within my constraints. However, the updated version of your repository now requires input images to be 512x512 pixels, and attempting to use smaller images results in a mismatch error. Unfortunately, I do not have access to a GPU with enough VRAM to accommodate 512x512 images.

Furthermore, I have encountered the following error, which occurs when attempting to use the updated code:

**Traceback (most recent call last):**
  File "/opt/conda/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "animatediff/AnimateDiff-I2V/scripts/animate.py", line 258, in <module>
    main(args)
  File "animatediff/AnimateDiff-I2V/scripts/animate.py", line 208, in main
    sample = pipeline(
  File "/opt/conda/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "animatediff/AnimateDiff-I2V/animatediff/pipelines/stablediffusion_controlnet_animatediff_pipeline.py", line 605, in __call__
    down_block_res_samples, mid_block_res_sample = controlnet_.forward(
  File "AnimateDiff-I2V/sd_lib/controlnet/controlnet_api.py", line 87, in forward
    down_block_res_samples, mid_block_res_sample = self.model(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/diffusers/models/controlnet.py", line 771, in forward
    sample = sample + controlnet_cond
**RuntimeError: The size of tensor a (60) must match the size of tensor b (64) at non-singleton dimension 3**

Thank you for your attention to this matter, and I look forward to your response. If you need any further information or if there is a more appropriate channel for discussing this, please let me know.

Best regards,

**Comment by ykk648** [comment]
shape infer bug fixed https://github.com/ykk648/AnimateDiff-I2V/commit/3abe28f4b87717fce79c72f96b2a98d79b934abf , I have tested both w-controlnet/wo-controlnet infer on 480*480 resolution, it works well
